var annotated_dup =
[
    [ "xpp", null, [
      [ "AtomMapper", "classxpp_1_1AtomMapper.html", "classxpp_1_1AtomMapper" ],
      [ "ButtonEvent", "classxpp_1_1ButtonEvent.html", null ],
      [ "CachedAtom", "classxpp_1_1CachedAtom.html", "classxpp_1_1CachedAtom" ],
      [ "ClassHints", "classxpp_1_1ClassHints.html", null ],
      [ "ClientMessageEvent", "classxpp_1_1ClientMessageEvent.html", "classxpp_1_1ClientMessageEvent" ],
      [ "ConfigureEvent", "classxpp_1_1ConfigureEvent.html", "classxpp_1_1ConfigureEvent" ],
      [ "Coord", "structxpp_1_1Coord.html", null ],
      [ "Event", "classxpp_1_1Event.html", "classxpp_1_1Event" ],
      [ "Extent", "structxpp_1_1Extent.html", null ],
      [ "FocusChangeEvent", "classxpp_1_1FocusChangeEvent.html", null ],
      [ "GraphicsContext", "classxpp_1_1GraphicsContext.html", "classxpp_1_1GraphicsContext" ],
      [ "Init", "structxpp_1_1Init.html", null ],
      [ "InputEvent", "classxpp_1_1InputEvent.html", "classxpp_1_1InputEvent" ],
      [ "KeyEvent", "classxpp_1_1KeyEvent.html", null ],
      [ "Pixmap", "classxpp_1_1Pixmap.html", "classxpp_1_1Pixmap" ],
      [ "PointerMovedEvent", "classxpp_1_1PointerMovedEvent.html", null ],
      [ "Property", "classxpp_1_1Property.html", "classxpp_1_1Property" ],
      [ "PropertyEvent", "classxpp_1_1PropertyEvent.html", "classxpp_1_1PropertyEvent" ],
      [ "PropertyTraits", "classxpp_1_1PropertyTraits.html", "classxpp_1_1PropertyTraits" ],
      [ "PropertyTraits< AtomID >", "classxpp_1_1PropertyTraits_3_01AtomID_01_4.html", null ],
      [ "PropertyTraits< const char * >", "classxpp_1_1PropertyTraits_3_01const_01char_01_5_01_4.html", null ],
      [ "PropertyTraits< int >", "classxpp_1_1PropertyTraits_3_01int_01_4.html", null ],
      [ "PropertyTraits< std::vector< AtomID > >", "classxpp_1_1PropertyTraits_3_01std_1_1vector_3_01AtomID_01_4_01_4.html", null ],
      [ "PropertyTraits< std::vector< ELEM > >", "classxpp_1_1PropertyTraits_3_01std_1_1vector_3_01ELEM_01_4_01_4.html", null ],
      [ "PropertyTraits< std::vector< int > >", "classxpp_1_1PropertyTraits_3_01std_1_1vector_3_01int_01_4_01_4.html", null ],
      [ "PropertyTraits< std::vector< utf8_string > >", "classxpp_1_1PropertyTraits_3_01std_1_1vector_3_01utf8__string_01_4_01_4.html", null ],
      [ "PropertyTraits< utf8_string >", "classxpp_1_1PropertyTraits_3_01utf8__string_01_4.html", null ],
      [ "PropertyTraits< WinID >", "classxpp_1_1PropertyTraits_3_01WinID_01_4.html", null ],
      [ "RawProperty", "structxpp_1_1RawProperty.html", "structxpp_1_1RawProperty" ],
      [ "RootWin", "classxpp_1_1RootWin.html", "classxpp_1_1RootWin" ],
      [ "SelectionEvent", "classxpp_1_1SelectionEvent.html", "classxpp_1_1SelectionEvent" ],
      [ "SelectionRequestEvent", "classxpp_1_1SelectionRequestEvent.html", "classxpp_1_1SelectionRequestEvent" ],
      [ "SetWindowAttributes", "classxpp_1_1SetWindowAttributes.html", null ],
      [ "SizeHints", "classxpp_1_1SizeHints.html", null ],
      [ "utf8_string", "structxpp_1_1utf8__string.html", null ],
      [ "VisibilityEvent", "classxpp_1_1VisibilityEvent.html", null ],
      [ "WindowManagerHints", "classxpp_1_1WindowManagerHints.html", null ],
      [ "WindowSpec", "structxpp_1_1WindowSpec.html", null ],
      [ "X11Exception", "structxpp_1_1X11Exception.html", "structxpp_1_1X11Exception" ],
      [ "XColor", "classxpp_1_1XColor.html", "classxpp_1_1XColor" ],
      [ "XCursor", "classxpp_1_1XCursor.html", "classxpp_1_1XCursor" ],
      [ "XDisplay", "classxpp_1_1XDisplay.html", "classxpp_1_1XDisplay" ],
      [ "Xpp", "classxpp_1_1Xpp.html", "classxpp_1_1Xpp" ],
      [ "XWindow", "classxpp_1_1XWindow.html", "classxpp_1_1XWindow" ],
      [ "XWindowAttrs", "classxpp_1_1XWindowAttrs.html", null ]
    ] ]
];