Import('env')

libenv = env.Clone()
public_includes = Dir(".").srcnode().abspath + "/../include"
libenv.Append(CPPPATH = public_includes)
# automatically include the export header to create less noise
libenv.Append(CCFLAGS = ["-include", "X++/dso_export.h"])
libenv.Append(CCFLAGS="-fvisibility=hidden")
libenv.Append(CCFLAGS="-DXPP_EXPORT")
libenv.Append(CPPPATH=["."])
libenv.ConfigureForLib('libcosmos')

libxpp_srcs = env.GatherSources(suffixes=[".cxx"])

libxpp = libenv.SharedLibrary(
    "X++",
    libxpp_srcs
)

env.RegisterLibConfig('libX++', libxpp, {
    "CCFLAGS": ["-DXPP_API="],
    "CPPPATH": [public_includes],
    "LIBS": ["X11"]
})
