name: Build libxpp and run unit tests
on: [push, pull_request]
jobs:
  build_libxpp:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check image version
        run: |
          cat /etc/os-release
      - run: echo "The name of your branch is ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: '0'
      - run: echo "Cloned repository"
      - name: Install build tools
        run: sudo apt-get install -y scons build-essential clang doxygen flake8 libx11-dev pkg-config
      - name: Compile and test various native build configurations
        # skip 32-bit and static linking builds
        # the GitHub Ubuntu runner image uses some strange repository
        # configuration, so that g++-multilib cannot be installed.
        #
        # the clang toolchain has some strangeness in it which breaks the
        # static linking build, but it works on vanilla Ubuntu 24.04
        #
        # it is hard to come by the images used by GH runner to test it
        # locally, thus I did not investigate this more deeply
        run: |
          ./libcosmos/scripts/check.py --skip-32bit --skip-static
      # the runner's doxygen for some reason doesn't support a -q switch
      #- name: build doxygen
      #  run: |
      #    scons doxygen
